---
name: Update metrics 📊
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Mildly interesting facts 🤨
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.WORK }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          config_timezone: Asia/Mumbai
          name: Example
      - name: GitHub stats 🎉
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.WORK }}
          base: header, repositories
          plugin_lines: yes
      - name: Achievements 🏁
        uses: lowlighter/metrics@latest
        with:
          filename: achievements.svg
          token: ${{ secrets.releases }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: >-
            polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
            scripter, packager, explorer, infographile, manager
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
